name: ğŸ‘€ Code Quality
on:
  pull_request:
    branches:
      - master
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: ğŸ”½ Download project
        uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: ğŸ  Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version-file: .nvmrc

      - name: ğŸ‘·â€â™‚ï¸ Install dependencies
        run: |
          npm ci

      # - name: ğŸ”… Prettier, Code Syntax Standard
      #   run: |
      #     echo "Recuerda tener instalado Prettier como formateador de cÃ³digo en tu Editor de texto"
      #     echo "Este cÃ³digo usarÃ¡ como estÃ¡ndar la indentaciÃ³n de Prettier."
      #     echo "Para solucionar tu indentaciÃ³n, ejecuta npm run sintax:fix"
      #     npm run sintax:test

      # - name: ğŸ‘€ Project Standards
      #   run: |
      #     npm test

      - name: ğŸ‘€ Code Quality
        run: |
          echo "Se revisarÃ¡ la calidad del cÃ³digo para que la consola no tenga warnings ni errores."
          echo "Se validarÃ¡ que no existan variables sin usar, console.logs, malos estÃ¡ndares de cÃ³digo, etc."
          npm run lint

      - name: ğŸ“¦ Build project
        env:
          CI: false
        run: |
          npm run build
